### ISSUE TITLE
Add config

### ISSUE THREAD

**Issue by Pietagorh** [Pietagorh/DraftBotHelper#3]
- [ ] Create tables in database

- [ ] auto/ask/off for each reminder #1
- [ ] Choose channel for reminders #1
- [ ] log/cache/off for all tracking #2
- [ ] Turn on/off each util #4
